### ISSUE TITLE
Prüfung Observation.code

### ISSUE THREAD

**Issue by f-peverali** [gematik/spec-ISiK-Vitalparameter-und-Koerpermasze#120]
Zu prüfen sind im ISiK Modul Vitalparameter die Observation.code Elemente.

Diese sollten übereinstimmen mit den Observation.code aus Mio42 Projekt DIGA Toolkit 1.1.0. (bzw. folgende).

Falls hier Abweichungen herrschen, sollten diese konsolidiert werden.

Hintergrund:

DiGA Toolkit hat autonome Release-Zyklen.

Perspektivisch sollte Gesamtprojekt mio42 Diga Toolkit mit ISiK Vitalparameter enger abgestimmt werden.
```[tasklist]
### Tasks
- [ ] PTDATA-712
```

**Comment by f-peverali** [comment]
Priorität zu klären @alexzautke , @MaxMTheilig hat ihr dazu eine Meinung

**Comment by f-peverali** [comment]
Bevor wir die Annahme oben weiter verfolgen, sollten wir hier Szenarien klären und auch in den IG einfließen lassen. Was denkst Du @ylboerner ?

**Comment by ylboerner** [comment]
@f-peverali Ich denke, es macht Sinn hier einen kurzen Überblick zu erstellen. Das werde ich bis Ende nächster Woche erledigen. Prinzipiell macht es aber total Sinn, die für den selben Sachverhalt in Deutschland veröffentlichten Profile zu harmonisieren. Somit wären Implementierende mit einer Implementierung direkt konform zu mehreren Spezifikationen.

**Comment by ylboerner** [comment]
@f-peverali Folgende Codes sind in den beiden Spezifikationen enthalten: 


Profil  | ISiK Vitalparameter | DiGA Toolkit
-- | -- | --
Atemfrequenz | Loinc:9279-1 | Loinc:9279-1 + SNOMED:Binding
Blutdruck | Loinc:85354-9 | Loinc:85354-9 + SNOMED:75367002
EKG | Loinc:LP6244-0 | Kein Profil
GCS | Loinc:9269-2 | Kein Profil
Herzfrequenz | Loinc:8867-4 | Loinc:8867-4 + SNOMED:Binding
Körpergewicht | Loinc:9279-1 | Loinc:Binding + SNOMED:Binding
Körpergröße | Loinc:8302-2 | Loinc:Binding + SNOMED:Binding
Köpertemperatur | Loinc:8310-5 | Loinc:8310-5 + SNOMED:Binding
Kopfumfang | Loinc:9843-4 | Loinc:9843-4 + SNOMED:Binding
Sauerstoffsättigung | Loinc:2708-6 | Loinc:2708-6 + SNOMED:431314004

Auf dieser Grundlage können wir folgende Feststellungen machen: 
1. In insgesamt 6 Profilen des DiGA Toolkits sind Slices für Loinc und/oder SNOMED CT enthalten, aber keine Codes festgelegt, sondern Bindings. Eine Angleichung mit den Vitalparametern wird hier schwer, da wir alle Bindings übernehmen müssen oder uns für einen Code aus dem KBV ValueSet Binding entscheiden sollten.
2. Falls ein fester LOINC Code enthalten ist, stimmt dieser derzeit zu 100% mit dem ISiK Modul Vitalparameter überein. Problematisch ist allerdings, dass die Doppekodierung in der DiGA Spezifikation verpflichtend ist, dadurch sind ISiK und DiGA nicht miteinander kompatibel.

**Folgende nächste Schritte:**

- [ ] Eine Kompatibilität ist nur gegeben, wenn die Doppelkodierung in ISiK verpflichtend wird (+ entsprechender Auswahl des Codes aus dem jeweiligen Binding) oder die Doppelkodierung im DiGA Toolkit nicht mehr verpflichtend ist. Ich schlage daher vor, dass wir dies mit @alexzautke und @patrick-werner im nächsten Meeting besprechen.

**Comment by ylboerner** [comment]
Zusätzliche Information: Die Begründung für die Herstellung der Kompatibilität muss im IG festgehalten werden. Dies ist für Anwender leider sonst nicht nachvollziehbar.

**Comment by f-peverali** [comment]
> Zusätzliche Information: Die Begründung für die Herstellung der Kompatibilität muss im IG festgehalten werden. Dies ist für Anwender leider sonst nicht nachvollziehbar.

In diesem Fall zum Beispiel: "Da mittelfristig auch eine Interoperabilität zwischen KIS und EPA mitsamt strukturierten Vitalparametern ermöglicht werden soll, werden hier die ISIK Vitalparameter Profile entlang der Elemente Observation.code harmonisiert mit den KBV/MIO Profilen (in Version ...)."

**Comment by ylboerner** [comment]
@f-peverali Ja, das hört sich gut an. Ich würde 'harmonisieren' ersetzen durch 'angleichen' oder 'näher aneinander bringen' aber prinzipiell passt das 👍 Habe es auf meine Liste mit aufgenommen.

**Comment by ylboerner** [comment]
Die Basisprofile werden mittels diesem PR angepasst: https://github.com/hl7germany/basisprofil-de-r4/pull/512

**Comment by ylboerner** [comment]
Die vorliegenden Codes werden direkt in die ISiK Profile eingepflegt. Der weitere Arbeitsstand wird hier dokumentiert: https://github.com/gematik/spec-ISiK-Vitalparameter-und-Koerpermasze/issues/74
