### ISSUE TITLE
Vorschlag Kommentierungsphase: Doppelkodierung mit SNOMED CT (Stufe 4?)

### ISSUE THREAD

**Issue by ylboerner** [gematik/spec-ISiK-Vitalparameter-und-Koerpermasze#74]
TBD ob dies umgesetzt wird nach der Kommentierungsphase.
```[tasklist]
### Tasks
- [ ] PTDATA-683
```

**Comment by f-peverali** [comment]
Was genau sollte umgesetzt werden ? Welche Stelle ist gemeint?

**Comment by ylboerner** [comment]
Hallo @f-peverali. In jedem Vitalparameter Profil ist aktuell eine Kodierung mit LOINC verpflichtend mittels Slice gesetzt: 
<img width="743" alt="Screenshot 2022-10-21 at 11 45 15" src="https://user-images.githubusercontent.com/39551832/197236596-44422eea-b7d0-42ca-a418-88eddc4ff9ae.png">

Im internationalen und Forschungskontext wird jedoch häufig SNOMED CT anstatt LOINC verwendet. Wir haben deshalb überlegt, in jedem Vitalparameter Profil eine Doppelkodierung mit SNOMED CT zu implementieren. Bisher wurde dies aus Zwecken der Simplifizierung allerdings nicht getan.

**Comment by alexzautke** [comment]
Bitte beachten, dass die KBV sich wünscht, dass diese Kodierung in den Deutschen Basisprofilen umgesetzt wird: https://github.com/hl7germany/basisprofil-de-r4/issues/276

**Comment by f-peverali** [comment]
Ggf. warten auf Umsetzung in Basisprofile DE?

**Comment by f-peverali** [comment]
@AnsgarHoeper hast Du hierzu eine Meinung?

**Comment by f-peverali** [comment]
Kodierung in ISiK mit Slice nur für Körpergewicht derzeit - alle anderen Profile haben fest-codierte Patterns

**Comment by f-peverali** [comment]
@alexzautke gibt es hier eine Möglichkeit ein Code.coding mit SNOMED einzuführen, ohne die Basisprofile zu enterben? Meiner Meinung nach nicht... dann die Frage: ist es das Wert? FYI @jcaumann

**Comment by alexzautke** [comment]
Wenn ich das richtig sehe haben die meisten Profile ein Open Slicing auf .code.coding. Somit könnte problemlos im ISiK Profil ein weiter Slice hinzugefügt werden. Komisch ist, dass z.B. der Kopfumfang kein Slicing hat. Sollte man nochmal überprüfen.

**Comment by f-peverali** [comment]
@alexzautke könnten wir das für TC FHIR auf die Agenda setzen?

**Comment by ylboerner** [comment]
@f-peverali Sollte meiner Meinung nach zu 100% verfolgt werden. Eine Doppelkodierung ist sicherlich nicht nur von der KBV gewünscht sondern auch von anderen Parteien. Die große Frage ist, welche der Slices man verpflichtend macht.

**Comment by jcaumann** [comment]
Das Problem mit der Mehrfachkodierung bei Vitalwerten schlägt auch massiv bei der Umsetzung des § 374a SGB V zu. Hier hatten wir erst neulich aus dem DiGA.Pro-Projekt heraus einen Workshop mt BfArM, MIO42 und gematik, auf dem einige Ideen (Doppelkodierung, ValueSets, "Basis"-Codes plus Plicht-Atribute, Constraints, etc.) diskutiert wurden. Fazit: alles nicht so einfach...
Da wir ja nicht jetzt alle seit 10 Jahren bekannten Probleme in 10 Tagen lösen müssen, bin ich sehr dafür, bei diesem Thema zunächst noch einmal zu schauen, wer davon alles betroffen ist und welche konkreten Rahmenbedingungen und Anforderungen es da gibt und wie eine für alle passende oder zumndest dann weiter profilierbare Lösung aussehen kann. Ansonsten hat man nachher für MII, ISiK, § 374a, etc. lauter verschiedene Lösungen und nichts ist gewonnen.

**Comment by ylboerner** [comment]
Optionale SNOMED-CT Kodierung wird hier in den Basisprofilen hinzugefügt: https://github.com/hl7germany/basisprofil-de-r4/pull/512

Im nächsten Schritt werden die ISiK Profile angepasst.

**Comment by patrick-werner** [comment]
mittlerweile umgesetzt
